# Configuration for each scraper target
# Note: Selectors will need to be updated periodically as websites change.
# In config/scrapers.yaml
# In config/scrapers.yaml
# In config/scrapers.yaml

# Search URL template for Amazon
amazon:
  base_url: "https://www.amazon.com/s?k={query}"
  product_container: '[data-component-type="s-search-result"]'
  data_selectors:
    # These CSS selectors target individual elements within each product block
    title: "span.a-size-medium.a-color-base.a-text-normal"
    price: "span.a-price > span.a-offscreen"
    url: "a.a-link-normal.s-underline-text.s-underline-link-text.s-link-style.a-text-normal"
    rating: "span.a-icon-alt"
  type: "selenium"

ebay:
  base_url: "https://www.ebay.com/sch/i.html?_nkw={query}"
  # Scrapy will handle this one
  type: "scrapy"

# BestBuy has a fairly static structure that's easier to parse with BeautifulSoup
bestbuy:
  # A simpler, more static-friendly site for BeautifulSoup/Requests
  base_url: "https://www.bestbuy.com/site/searchpage.jsp?st={query}"
  product_container: ".sku-item"
  data_selectors:
    title: "h4.sku-title a"
    price: ".priceView-hero-price.priceView-customer-price span[aria-hidden='true']"
    url: "h4.sku-title a"
    rating: ".average-rating" # Not always present
  type: "static"
